[build]
command = "deno upgrade && deno task build"
publish = "dist"

[functions]
node_bundler = "esbuild"
directory = "src/routes"
included_files = ["src/views/*.pug"]

[[redirects]]
from = "/"
to = "/.netlify/functions/index"
